### PR TITLE
Simplify pull request template.

### PR DESCRIPTION
**Pull request by dj2**
# Summary | Résumé

This PR removes most of the content from the pull request template. The
headers for summary and testing remain but all other content has been
removed.

In general, folks were deleting all the content as they created their
PRs so the full set of information was taking more time then it was
saving.

### CODE REVIEW

**Comment by CalvinRodo** [comment]
My understanding is that the PR templates are more for external contributors than for CDS employees, since that is the case we might want to leave the instructions for anyone interacting with our repos.

**Comment by dj2** [comment]
Possibly? But they also add work to every PR we put up in that we need to clear out most of the template. It seems like if we wanted those instructions they'd be better served in the CONTRIBUTING file? Would moving them over there work for you?

**Comment by CalvinRodo** [comment]
Possibly, I would question if folks read those, however that begs the question if they don't read that would they read the PR template?

**Comment by dj2** [comment]
Personally, I'm more inclined to read the CONTRIBUTING file when I start putting together a PR then the PR template as I've already got my commit message and stuff written at that point.

**Pull request closed without merging**
