### PR TITLE
feat: add a .github folder to the template

### PR DESCRIPTION
**Pull request by CalvinRodo**
- mv the pr template into the .github folder
- add the label workflow to the template project

### CODE REVIEW

**Review by dj2 — APPROVED** [review]

**Comment by dj2** [comment]
Reading Max's reply to https://github.com/cds-snc/.github/issues/14, I'm not sure if this is the right thing to do?

**Review by wmoussa-gc — APPROVED** [review]

**Comment by patheard** [comment]
It depends how we use the project template.  If we clone it locally as the basis for a new project and then push it back up, this works.  

If we want to [share workflow templates](https://docs.github.com/en/actions/learn-github-actions/sharing-workflows-with-your-organization#creating-a-workflow-template) with other project's we'd use a different approach:

```sh
./workflow-templates
    workflow-name.yml
    workflow-name.properties.json

```

I'm looking at the same thing for cds-snc/site-reliability-engineering#194.

**Comment by dj2** [comment]
Yup, but I don't think we've been using this template that way, historically. There are a lot of repos which don't have the pull request template and just get it from here.

I'd prefer to switch to what you're saying, I really don't like the magic of the files appearing from this folder. But, we'd need to make sure all of our public folders have the various template files committed before we make this change (and we should probably rename this from .github to remove confusion)

**Comment by patheard** [comment]
I don't like the magic either, but I do like doing things the GitHub Way™

I'm going to do some investigation around what it looks like if we always use this template to create new projects.  Maybe there's a way we can have the best of both worlds:

1. Creating new projects from the `.github` template gives us all the files in the expected spots; and
2. Existing projects can still reference those template files rather than us having to go back and add a lot of missing things people have come to expect automagically.

**Comment by dj2** [comment]
In this case, I think the GitHub way is wrong. If I clone the repo, I want the CONTRIBUTING files and things locally which you lose with this. I can understand why they added it, if you're a large org with lots of legacy folders this applies them across the board. I think we should just mandate that all repos must have these projects and not use the magic way.

**Comment by dj2** [comment]
Heh, I actually approve of this change, I just think we should also rename the .github project to cds-template or something and stop having it default in the files.

**Comment by patheard** [comment]
Yeah, we'll get this added to a cds-template project along with the S3 backup workflow.

**Pull request closed without merging**
