### PR TITLE
French translation of MIT license

### PR DESCRIPTION
**Pull request by jeffmaher**
Thanks to @EliseKa for [the translation](https://docs.google.com/document/d/1fzMyPfdW8MZPdZ-5khmaMJNv6YNCCivuzlKOs7MM9jk/edit?ts=5d79430a).

### CODE REVIEW

**Comment by jeffmaher** [comment]
@mcman12 or @sboisvert : Could you review? (I don't have access rights to assign a reviewer)

**Comment by nschonni** [comment]
Note, this doesn't match the previous translation used by WET https://github.com/wet-boew/wet-boew/blob/master/Licence-fr.txt
It's not usually a good idea to translate legal documents without a lawyer (which maybe @EliseKa is)

@shadewyrm maybe this is something we need to address in https://github.com/canada-ca/open-source-logiciel-libre

**Comment by sboisvert** [comment]
I find the CDS version a bit more clear as it's less jargony and the wording is more straightforward, but, I'm not a lawyer. That being said, in terms of does it make sense and is it understandable in French, yes and I'd be happy to merge it. 
We can improve upon it later with feedback from the community as mentioned by @nschonni

**Comment by jeffmaher** [comment]
Thanks @nschonni and @sboisvert ! I'll grab the text of the Wet one and update this PR.

**Comment by jeffmaher** [comment]
Updated with the text from the WET copy.

**Pull request merged**
